### ISSUE TITLE
Support documentation in multiple languages

### ISSUE THREAD

**Issue by civilizeddev** [ncthbrt/nact.xyz#23]
Hi @ncthbrt,

I am a developer working for [Musma Tech Lab.](https://www.musma.net/?l=en) in [Korea](https://en.wikipedia.org/wiki/South_Korea).

I have been searching for an actor implementation, running on Node platform because I believe actor system will be useful in our product.

Fortunately I have reached here, [nact.io](https://nact.io/)

I firstly reviewed the documents provided here (the JavaScript part) and translated them into Korean to share with my colleagues.

You can see it in our tech blog: https://musma.github.io/tag/#nact-io
(I apologize for not getting your permission for translation in advance)

If you are okay, I will contribute the translations.

I hope nact would get introduced into JavaScript/Node community in Korea.

Thank you.

**Comment by ncthbrt** [comment]
Hi @civilizeddev 
Too cool! What can I do to help support this? I'm not that experienced with localization.

**Comment by civilizeddev** [comment]
@ncthbrt 
It looks like you use [gatsbyjs](https://www.gatsbyjs.org/) for the homepage.

I am afraid I am new to gatsbyjs. But I believe there would be a way to route *.md files according to the language selected.

If you are familiar with it, could you find any idea from these articles:
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18next/
- https://github.com/gatsbyjs/gatsby/issues/9119
- https://blog.significa.pt/i18n-with-gatsby-528607b4da81

Thank you.

**Comment by ncthbrt** [comment]
@civilizeddev: maybe a good first start would be if you made a PR containing the markdown files of the tutorials, and I can work to integrate them with the site code.

Once that's done, we can move on to translating the other pages

**Comment by ncthbrt** [comment]
Hi @civilizeddev. I've started working towards multilingual support on the site itself. I need a little help however. At the moment I'm hardcoding the names of the chapters, which are: `'Introduction', 'Core Concepts', 'Persistence', 'Production'`. I'd like the chapter names to also be internationalized. 

Another thing that I'm struggling a little with is that there actually are two dimensions of language here: The written and programming language (javascript and reasonml). I'm not entirely sure how to change the UI to support this, without it being confusing, especially as I don't yet have ReasonML docs in Korean.

**Comment by ncthbrt** [comment]
@civilizeddev I've now added a language picker to the website. I'm still missing a few translations, like the link header and chapter names. Please let me know what you think. Thanks for the translations..

**Comment by civilizeddev** [comment]
@ncthbrt

Wonderful. It looks great.
If you need anything else, please let me know.

Thank you.

## The remaining:

- [main page in ko_KR](https://musma.github.io/2019/02/19/nact-main.html).

## Translations:

### Link

- `LANGUAGE` -> `언어`
- `BLOG` -> `블로그`
- `COMMUNITY` -> `커뮤니티`
- `GITHUB` -> `GITHUB`

### Chapter names

- `Introduction` -> `소개`
- `Core Concepts` -> `핵심 개념`
- `Persistence` -> `퍼시스턴스`
- `Production` -> `실무` (different word, but more relevant in meaning)

**Comment by ncthbrt** [comment]
Reopening this issue until we're 100% there. Still need to do the header, home pages, and possibly the community page.

**Comment by ncthbrt** [comment]
@civilizeddev Would you be fine with a solution like putting the korean home page at something like `nact.io/ko_kr/home` or would you prefer something more dynamic?

**Comment by ncthbrt** [comment]
I've made the korean homepage: https://nact.io/ko_kr/ 
Please be on the look out for any errors on my part.


I removed the blog because it's not that useful, but added a korean community page. Right now that's just in English, but if you'd like to translate it, and possibly add links to any korean communities that could help, feel free. You can find the community page here: https://github.com/ncthbrt/nact.io/blob/master/src/pages/ko_kr/community.jsx

**Comment by civilizeddev** [comment]
@ncthbrt  in the community page, it says

> "Project management uses waffle.io."

But I found that [waffle.io is closing its doors](https://waffle.io/closing-its-doors) and the team board doesn't seem working.

Do you have any plan for this?

Once you update the community page, I'll follow it up.

Thank you.

**Comment by ncthbrt** [comment]
I think I will remove mention of waffle and stick to just using GitHub for
that sort of thing going forward. GitHub has really improved that feature
set.
